version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: tools/server/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default-network

networks:
  default-network:
    driver: bridge
