version: '3.9'

services:
  server:
    build:
      context: tools/server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default-network

networks:
  default-network:
    driver: bridge
